---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: pyspark-pi
  namespace: default
spec:
  version: "1.0"
  sparkImage:
    productVersion: 3.3.0
  mode: cluster
  mainApplicationFile: local:///stackable/spark/examples/src/main/python/pi.py
  driver:
    config:
      resources:
        memory:
          limit: "1Gi"
  executor:
    replicas: 1
    config:
      resources:
        memory:
          limit: "1Gi"