apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  # The name of the catalog as it will appear in Trino
  name: iceberg
  labels:
    trino: simple-trino
spec:
  connector:
    # Specify iceberg here when defining a iceberg catalog
    iceberg:
      metastore:
        configMap: hive-postgres-s3-metastore-default
      s3:
        inline:
          host: test-minio
          port: 9000
          accessStyle: Path
          credentials:
            secretClass: hive-s3-secret-class